# srcs/docker-compose.yml

services:
  nginx:
    build:
      context: ./requirements/nginx/
      args:
        SSL_CERT_FOLDER: ${SSL_CERT_FOLDER}
        SSL_CERT_PATH: ${SSL_CERT_PATH}
        SSL_KEY_PATH: ${SSL_KEY_PATH}
        SSL_CSR_PATH: ${SSL_CSR_PATH}
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wp-php
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - nginx

volumes:
  wordpress_data:

networks:
  inception_network:
