# srcs/docker-compose.yml

version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx/
      args:
        SSL_CERT_FOLDER: ${SSL_CERT_FOLDER}
        SSL_CERT_PATH: ${SSL_CERT_PATH}
        SSL_KEY_PATH: ${SSL_KEY_PATH}
        SSL_CSR_PATH: ${SSL_CSR_PATH}
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception_network:
    driver: bridge
